### ISSUE TITLE
hashed user identifier

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/smaug#102]
Smaug should include some sort of unique user identifier in the user-blob, that doesn't reveal the actual username (maybe a salt and some sort of hashing algo).

**Comment by adamtulinius** [comment]
A cryptographically secure identifier can't be generated on the fly, because of the time taken to generate it will slow Smaug down way too much.

If Smaug has to do this, the identifier should be cached somehow, which is kinda annoying with the current `userstore` architecture.

**Comment by rasmuserik** [comment]
... maybe smaug should supply a salt instead, and then the serviceprovider could generate the identifier when the user endpoint is executed.

**Comment by rasmuserik** [comment]
I have added code for generating the user id in the service provider, - assumes that context.userstatus.salt is set.
