### ISSUE TITLE
anonymous user does not work

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/smaug#124]

**Comment by adamtulinius** [comment]
Both totally anonymous (username='@') and library-specific anynomous (username='@libraryId') seems to fail.

**Comment by adamtulinius** [comment]
Update: Library-specific anynomous (username='@libraryId') does work, as long as one remembers to set password='@libraryId'.

**Comment by adamtulinius** [comment]
Update: Totally anonymous (username='@') also works, but the config-file must use a valid default library id.

**Comment by adamtulinius** [comment]
Reopening, so we can track the config update.

**Comment by rasmuserik** [comment]
:) nice, now things works when I test with anonymous user :+1:
