### ISSUE TITLE
limit access to configuration retrieval

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/smaug#15]
configuration retrieval should not be exposed to the world wide web.
Either
1. make a whitelist of addresses to allow requests from
2. use OAuth for this as well

**Comment by KiraH** [comment]
Jeg tror den er lavet. Der er en anden url på en anden port, hvor man kan hente sin konfiguration. Spørgsmålet er om den ikke er sat op så den kun er tilgængelig indefra. Men det kan vi lige tjekke.
