### ISSUE TITLE
Make it possible to inherit config from other clients 

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/smaug#178]
Instead of having to administer 100 different clients it should be possible to have a hieraki of configurations.

**Comment by KiraH** [comment]
Mja, det er sådan Biblos konfig er bygget op og det er pænt uoverskueligt.

Måske vi hellere vil have mulighed for søgning i konfigurationerne og evt. erstat er konfigurationer på flere valgte klienter på en gang. Altså noget udbygget admin.

Men vi skal i hvert fald nok have diskuteret hvordan vi vil håndtere de mange klient konfigurationer.
