### ISSUE TITLE
Oprydning af udløbne tokens

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/smaug#192]
Pt. fjernes udløbne token ikke fra databasen, så en afklaring af om det skal være så, eller der skal ske en oprydning med en eller anden frekvens - alternativt noget garbage-collection ifm token-trækning.

Evt. fremtidige CGI-baserede klienter vil måske trække et nyt token for hver eneste forespørgsel, efterladende en masse tokens som ikke vil blive brugt mere. Oprydningningen vil håndtere disse, men som det er nu, har samtlige tokens identisk levetid (en måned). Så, en overvejelse af om det skal være muligt at have trimbar levetid for et token, og derved bedre mulighed for oprydning.

**Comment by KiraH** [comment]
Jeg har nu oprettet et oprydningsjob, der fjerner alle udløbne tokens hver nat på stg og prod.

Den nederste del i dette issue er der allerede et andet issue på #161
