### ISSUE TITLE
Moreinfo skal opgraderes til 2.11

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/smaug#203]
1. maj lukker alle andre versioner end den nyeste 2.11.

**Comment by KiraH** [comment]
Det kunne være smart, hvis vi kunne få lavet et udtræk over hvilke versioner der benyttes i smaug. Default konfiggen er let at se, men det er bøvlet hvis der er konfigureret noget nede i de enkelte klienter.

**Comment by KiraH** [comment]
done
