### ISSUE TITLE
Mails ved deploy

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/smaug#204]
Gælder alle produkter.

Vagten har behov for at kunne af eller be -kræfte at årsagen til en given alarm kan forklares med ændringer i driftsmiljøet.

Der skal sendes en mail til it-change@dbc.dk, når der sættes noget nyt i drift med følgende info: team, komponent, jenkins bygge nummer, server, dato/tid”.

**Comment by KiraH** [comment]
- Biblo[ ] 
- Serviceprovider v1 [ ]
- Serviceprovider v2 [ ]
- Serviceprovider v3 [ ]
- Smaug [ ]
- Adgangsplatformen [ ]
- Læsekompasset [ ]
- DK5 [ ]
- Metakompasset [ ]
-

**Comment by KiraH** [comment]
done
