### ISSUE TITLE
Smaug klient til Silkeborg

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/smaug#205]
I forbindelse med quiz skal der oprettes adgang for Silkeborg

**Comment by BettinaAndersen** [comment]
Send info til Bettina

**Comment by vibjerg** [comment]
@BettinaAndersen, Hvem skal være kontaktperson. Jeg skal bruge navn, email og gerne tlf.

**Comment by vibjerg** [comment]
Jeg sætter storage id til:
```
"storage": {
    "user": "{AGENCYID}-quiz"
  },
```

**Comment by BettinaAndersen** [comment]
Jeg slagger kontaktoplysninger til Silkeborg.

**Comment by vibjerg** [comment]
Klient er sendt til @BettinaAndersen
